---
# AmneziaWG interface name.
singbox_config_name: config

# Main sing-box configuration structure.
singbox_config:
  log: "{{ singbox_config_log }}"
  dns: "{{ singbox_config_dns }}"
  inbounds: "{{ singbox_config_inbounds }}"
  outbounds: "{{ singbox_config_outbounds }}"
  route: "{{ singbox_config_route }}"
  experimental: "{{ singbox_config_experimental }}"

# Logging settings.
singbox_config_log:
  level: error
  timestamp: true

# DNS configuration.
singbox_config_dns:
  final: quad9
  independent_cache: true
  servers:
    - tag: dumb
      type: tcp
      server: 8.8.8.8
    - tag: quad9
      type: https
      server: dns.quad9.net
      domain_resolver: dumb
  rules:
    - query_type: HTTPS
      action: predefined
      rcode: NOERROR

# Inbound listeners.
singbox_config_inbounds:
  - tag: tun
    type: tun
    stack: mixed
    address: 172.19.0.1/30
    auto_route: true
    strict_route: true
    auto_redirect: true
    auto_redirect_input_mark: "0x2023"
    auto_redirect_output_mark: "0x2024"
    endpoint_independent_nat: false
    interface_name: sb0

# Outbound connections.
singbox_config_outbounds:
  - tag: direct
    type: direct

# Routing settings.
singbox_config_route:
  final: direct
  auto_detect_interface: true
  default_domain_resolver:
    server: quad9

# Experimental features.
singbox_config_experimental:
  cache_file:
    enabled: true
