# Version of sing-box to download.
# renovate: datasource=github-releases depName=SagerNet/sing-box
singbox_download_version: "1.14.1"

# Mapping from system architecture to sing-box release architecture naming.
singbox_download_architecture_map:
  x86_64: amd64
  aarch64: arm64

# URL to download the sing-box archive.
singbox_download_url: "https://github.com/SagerNet/sing-box/releases/download/v{{ download_url_version }}/sing-box-{{ download_url_version }}-linux-{{ arch.value }}.tar.gz"
