---
# --- Identity ---
namespace: kasefuchs
name: general
version: 0.1.0

# --- Metadata ---
description: A collection of common Ansible roles used across my own projects.
readme: README.md
authors:
  - kasefuchs
license:
  - MIT
tags: []

# --- Links ---
repository: https://codeberg.org/kasefuchs/ansible-collection-general
homepage: https://codeberg.org/kasefuchs/ansible-collection-general
documentation: https://codeberg.org/kasefuchs/ansible-collection-general
issues: https://codeberg.org/kasefuchs/ansible-collection-general/issues

# --- Technical ---
dependencies: {}
build_ignore:
  - .idea
  - .vscode
  - .venv
