---
# Directory where AmneziaWG configuration stored.
amneziawg_install_config_dir: /etc/amnezia/amneziawg

# Path to the AmneziaWG tool binary.
amneziawg_install_binary: "{{ (common_binary_dir, 'awg') | ansible.builtin.path_join }}"

# Path to the AmneziaWG quick script.
amneziawg_install_script: "{{ (common_binary_dir, 'awg-quick') | ansible.builtin.path_join }}"
