- name: Download AmneziaWG go
  ansible.builtin.include_role:
    name: kasefuchs.general.download_oci
  vars:
    download_oci_dir: "{{ amneziawg_download_go_local_dir }}"
    download_oci_source: "{{ amneziawg_download_go_image }}"
    download_oci_version: "{{ amneziawg_download_go_version }}"

- name: Download AmneziaWG tools
  ansible.builtin.include_role:
    name: kasefuchs.general.download_oci
  vars:
    download_oci_dir: "{{ amneziawg_download_tools_local_dir }}"
    download_oci_source: "{{ amneziawg_download_tools_image }}"
    download_oci_version: "{{ amneziawg_download_tools_version }}"
