- name: Download AmneziaWG go
  ansible.builtin.include_role:
    name: kasefuchs.general.download_url
  vars:
    download_url_dir: "{{ amneziawg_download_go_local_dir }}"
    download_url_source: "{{ amneziawg_download_go_url }}"
    download_url_version: "{{ amneziawg_download_go_version }}"
    download_url_architecture_map: "{{ amneziawg_download_go_architecture_map }}"

- name: Download AmneziaWG tools
  ansible.builtin.include_role:
    name: kasefuchs.general.download_url
  vars:
    download_url_dir: "{{ amneziawg_download_tools_local_dir }}"
    download_url_source: "{{ amneziawg_download_tools_url }}"
    download_url_version: "{{ amneziawg_download_tools_version }}"
    download_url_architecture_map: "{{ amneziawg_download_tools_architecture_map }}"
