---
- name: Create AmneziaWG directories
  loop:
    - "{{ amneziawg_install_config_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
    owner: root
    group: root

- name: Extract AmneziaWG go archive
  when: amneziawg_install_go
  ansible.builtin.unarchive:
    src: "{{ amneziawg_download_go_local_file }}"
    dest: "{{ common_binary_dir }}"
    mode: "0755"
    owner: root
    group: root
    include: "{{ amneziawg_install_go_extract_include }}"
    extra_opts: "{{ amneziawg_install_go_extract_options }}"

- name: Install AmneziaWG kernel module
  when: amneziawg_install_kmod
  block:
    - name: Check current DKMS status for AmneziaWG module
      register: amneziawg_install_kmod_dkms_status
      failed_when: false
      changed_when: false
      ansible.builtin.command: dkms status -m amneziawg -v {{ amneziawg_download_kmod_version }}

    - name: Build and register AmneziaWG module in DKMS
      when: "amneziawg_download_kmod_version not in amneziawg_install_kmod_dkms_status.stdout"
      block:
        - name: Create temporary directory for kernel module
          register: amneziawg_install_kmod_tempdir
          ansible.builtin.tempfile:
            state: directory
            suffix: amneziawg

        - name: Extract AmneziaWG kernel module archive
          ansible.builtin.unarchive:
            src: "{{ amneziawg_download_kmod_local_file }}"
            dest: "{{ amneziawg_install_kmod_tempdir.path }}"
            mode: "0755"
            owner: root
            group: root
            include: "{{ amneziawg_install_kmod_extract_include }}"
            extra_opts: "{{ amneziawg_install_kmod_extract_options }}"

        - name: Prepare DKMS sources using Makefile
          community.general.make:
            chdir: "{{ amneziawg_install_kmod_source_dir }}"
            target: dkms-install
            params:
              WIREGUARD_VERSION: "{{ amneziawg_download_kmod_version }}"

        - name: Register AmneziaWG module in DKMS tree
          changed_when: true
          ansible.builtin.command: "dkms add -m amneziawg -v {{ amneziawg_download_kmod_version }}"

        - name: Compile AmneziaWG kernel module via DKMS
          changed_when: true
          ansible.builtin.command: "dkms build -m amneziawg -v {{ amneziawg_download_kmod_version }}"

        - name: Install compiled AmneziaWG module into the kernel
          changed_when: true
          ansible.builtin.command: "dkms install -m amneziawg -v {{ amneziawg_download_kmod_version }}"

- name: Install AmneziaWG tools
  block:
    - name: Extract AmneziaWG tools archive
      ansible.builtin.unarchive:
        src: "{{ amneziawg_download_tools_local_file }}"
        dest: "{{ common_binary_dir }}"
        mode: "0755"
        owner: root
        group: root
        include: "{{ amneziawg_install_tools_extract_include }}"
        extra_opts: "{{ amneziawg_install_tools_extract_options }}"

    - name: Install AmneziaWG service
      notify: Reload daemon
      block:
        - name: Install AmneziaWG service (systemd)
          when: ansible_facts.service_mgr == "systemd"
          ansible.builtin.template:
            src: awg-quick@.service.j2
            dest: /etc/systemd/system/awg-quick@.service
            owner: root
            group: root
            mode: "0644"
