- name: Download sing-box archive
  ansible.builtin.include_role:
    name: kasefuchs.general.download_url
  vars:
    download_url_dir: "{{ singbox_download_local_dir }}"
    download_url_source: "{{ singbox_download_url }}"
    download_url_version: "{{ singbox_download_version }}"
    download_url_architecture_map: "{{ singbox_download_architecture_map }}"
