- name: Enable K3s server service (systemd)
  when:
    - ansible_facts.service_mgr == "systemd"
    - k3s_server_group in group_names
  listen: Enable K3s server service
  ansible.builtin.systemd_service:
    name: k3s
    enabled: true

- name: Restart K3s server service (systemd)
  when:
    - ansible_facts.service_mgr == "systemd"
    - k3s_server_group in group_names
  listen: Restart K3s server service
  ansible.builtin.systemd_service:
    name: k3s
    state: restarted

- name: Enable K3s agent service (systemd)
  when:
    - ansible_facts.service_mgr == "systemd"
    - k3s_agent_group in group_names
  listen: Enable K3s agent service
  ansible.builtin.systemd_service:
    name: k3s-agent
    enabled: true

- name: Restart K3s agent service (systemd)
  when:
    - ansible_facts.service_mgr == "systemd"
    - k3s_agent_group in group_names
  listen: Restart K3s agent service
  ansible.builtin.systemd_service:
    name: k3s-agent
    state: restarted
