# AmneziaWG interface name.
amneziawg_config_instance: awg0

# Interface configuration parameters.
amneziawg_config_interface: "{{ undef('AmneziaWG interface configuration must be provided (amneziawg_config_interface)') }}"

# List of peer configurations.
amneziawg_config_peers: []

# Junk packets.
amneziawg_config_junk: {}

# Message paddings.
amneziawg_config_paddings: []

# Message headers.
amneziawg_config_headers: []

# Custom signature packets.
amneziawg_config_signatures: []

# Commands executed before interface is brought up.
amneziawg_config_hook_pre_up: []

# Commands executed after interface is brought up.
amneziawg_config_hook_post_up: []

# Commands executed before interface is brought down.
amneziawg_config_hook_pre_down: []

# Commands executed after interface is brought down.
amneziawg_config_hook_post_down: []
