# Extra options for extracting the AmneziaWG go archive.
amneziawg_install_go_extract_options:
  - --strip-components=3

# Files or directories to include when extracting.
amneziawg_install_go_extract_include:
  - usr/local/bin/amneziawg-go

# Extra options for extracting the AmneziaWG tools archive.
amneziawg_install_tools_extract_options:
  - --strip-components=3

# Files or directories to include when extracting.
amneziawg_install_tools_extract_include:
  - usr/local/bin/awg
  - usr/local/bin/awg-quick
